# Copyright (c) 2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';

use PostgreSQL::Test::Cluster;
use Test::More;

my $node = PostgreSQL::Test::Cluster->new('primary');
$node->init();
$node->append_conf(
	'postgresql.conf', qq[
autovacuum = off
log_min_messages = warning
]);
$node->start();
$node->safe_psql('template1', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

$node->safe_psql(
	'postgres',
	q[
		CREATE TABLE csnlog_truncate_test (
			id bigint GENERATED BY DEFAULT AS IDENTITY,
			payload text NOT NULL
		);
	]);

my $warmup_script = {
	'csnlog_truncate_warmup.pgb' =>
	  "INSERT INTO csnlog_truncate_test(payload) VALUES ('bulk');\n",
};

my $psql = $node->background_psql('postgres', on_error_stop => 1);
$psql->query_safe('BEGIN ISOLATION LEVEL REPEATABLE READ');
my $long_xid = $psql->query_safe('SELECT pg_current_xact_id();');
$long_xid =~ s/\s+//g;
like($long_xid, qr/^\d+$/, 'captured a long-running xid');

$node->pgbench(
	'--no-vacuum --client=4 --jobs=4 --transactions=25000',
	0,
	[],
	[],
	'pgbench warmup batch',
	$warmup_script);

$node->safe_psql('postgres', 'CHECKPOINT');

my $before_files = $node->safe_psql(
	'postgres',
	q[
		SELECT count(*)
		FROM pg_ls_dir('pg_csnlog')
	]);

cmp_ok($before_files, '>=', 3, 'warmup batch creates multiple pg_csnlog segments');

my $status_during = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$long_xid'::xid8);");
is($status_during, 'in progress', 'long xid stays visible while open');

$node->safe_psql('postgres',
	'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

my $after_files = $node->safe_psql(
	'postgres',
	q[
		SELECT count(*)
		FROM pg_ls_dir('pg_csnlog')
	]);

is($after_files, $before_files,
	'VACUUM stays within the conservative pg_csnlog floor');

my $frozen_with_holder = $node->safe_psql(
	'postgres',
	q[
		SELECT datfrozenxid::text::bigint
		FROM pg_database
		WHERE datname = current_database()
	]);

$status_during = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$long_xid'::xid8);");
is($status_during, 'in progress', 'open xid remains reportable after truncation');

$psql->query_safe('COMMIT');

my $status_committed = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$long_xid'::xid8);");
is($status_committed, 'committed', 'committed xid remains reportable before restart');

$node->safe_psql('template1', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');
$node->safe_psql('postgres',
	'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

my $after_release_files = $node->safe_psql(
	'postgres',
	q[
		SELECT count(*)
		FROM pg_ls_dir('pg_csnlog')
	]);

cmp_ok($after_release_files, '<=', $before_files,
	'VACUUM does not expand pg_csnlog after the horizon holder is released');

my $frozen_after_release = $node->safe_psql(
	'postgres',
	q[
		SELECT datfrozenxid::text::bigint
		FROM pg_database
		WHERE datname = current_database()
	]);

cmp_ok($frozen_after_release, '>', $frozen_with_holder,
	'releasing the holder lets VACUUM advance datfrozenxid further');

$node->stop('immediate');
$node->start();

my ($ret, $stdout, $stderr) = $node->psql(
	'postgres',
	"SELECT pg_xact_status('$long_xid'::xid8);");
is($ret, 0, 'post-restart xid status lookup does not error');
like($stdout, qr/^(?:committed)?\n?$/,
	'post-restart xid status is either committed or unavailable');

my $row_count = $node->safe_psql(
	'postgres',
	'SELECT count(*) FROM csnlog_truncate_test;');
is($row_count, '100000', 'all generated rows survive restart');

done_testing();
