# Copyright (c) 2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';

use PostgreSQL::Test::Cluster;
use Test::More;

sub csnlog_state
{
	my ($node) = @_;
	my $state = $node->safe_psql(
		'postgres',
		q[
			SELECT count(*), min(name), max(name)
			FROM pg_ls_dir('pg_csnlog') AS t(name)
		]);

	return split(/\|/, $state);
}

my $node = PostgreSQL::Test::Cluster->new('primary');
$node->init();
$node->append_conf(
	'postgresql.conf', qq[
autovacuum = off
max_prepared_transactions = 10
log_min_messages = warning
]);
$node->start();
$node->safe_psql('postgres',
	'ALTER DATABASE template0 ALLOW_CONNECTIONS true;');
$node->safe_psql('template1', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

$node->safe_psql(
	'postgres',
	q[
		CREATE TABLE csnlog_truncate_test (
			id bigint GENERATED BY DEFAULT AS IDENTITY,
			payload text NOT NULL
		);
	]);

my $initial_churn_script = {
	'csnlog_truncate_initial_churn.pgb' =>
	  "INSERT INTO csnlog_truncate_test(payload) VALUES ('bulk');\n",
};

my $post_prepare_churn_script = {
	'csnlog_truncate_post_prepare_churn.pgb' =>
	  "INSERT INTO csnlog_truncate_test(payload) VALUES ('bulk');\n",
};

my $post_release_churn_script = {
	'csnlog_truncate_post_release_churn.pgb' =>
	  "INSERT INTO csnlog_truncate_test(payload) VALUES ('bulk');\n",
};

$node->pgbench(
	'--no-vacuum --client=4 --jobs=4 --transactions=25000',
	0,
	[],
	[],
	'pgbench initial churn batch',
	$initial_churn_script);

$node->safe_psql('postgres', 'CHECKPOINT');

my ($initial_files, $initial_floor, $initial_tail) = csnlog_state($node);

cmp_ok($initial_files, '>=', 3,
	'initial churn creates multiple pg_csnlog segments');

my $prepared_gid = 'csnlog_truncate_witness';
my $prepared_payload = 'prepared witness';
my $psql = $node->background_psql('postgres', on_error_stop => 1);
$psql->query_safe('BEGIN');
$psql->query_safe(
	"INSERT INTO csnlog_truncate_test(payload) VALUES ('$prepared_payload');");
my $prepared_xid = $psql->query_safe('SELECT pg_current_xact_id();');
$prepared_xid =~ s/\s+//g;
like($prepared_xid, qr/^\d+$/, 'captured a prepared-xact witness xid');

$psql->query_safe("PREPARE TRANSACTION '$prepared_gid'");
$psql->quit;

my $prepared_xid_in_view = $node->safe_psql(
	'postgres',
	"SELECT transaction::text FROM pg_prepared_xacts WHERE gid = '$prepared_gid';");
is($prepared_xid_in_view, $prepared_xid,
	'pg_prepared_xacts exposes the outstanding retention witness');

my $status_during = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$prepared_xid'::xid8);");
is($status_during, 'in progress',
	'prepared xid stays reportable while it remains outstanding');

my $prepared_visible = $node->safe_psql(
	'postgres',
	"SELECT count(*) FROM csnlog_truncate_test WHERE payload = '$prepared_payload';");
is($prepared_visible, '0',
	'prepared rows stay invisible before COMMIT PREPARED');

$node->pgbench(
	'--no-vacuum --client=4 --jobs=4 --transactions=25000',
	0,
	[],
	[],
	'pgbench post-prepare churn batch',
	$post_prepare_churn_script);

$node->safe_psql('postgres', 'CHECKPOINT');

my ($before_files, $before_floor, $before_tail) = csnlog_state($node);

cmp_ok($before_files, '>', $initial_files,
	'post-prepare churn extends pg_csnlog beyond the prepared witness');
cmp_ok($before_tail, 'gt', $initial_tail,
	'post-prepare churn advances the pg_csnlog tail');

my $ordinary_holders = $node->safe_psql(
	'postgres',
	q[
		SELECT count(*)
		FROM pg_stat_activity
		WHERE datname = current_database()
		  AND pid <> pg_backend_pid()
		  AND (backend_xid IS NOT NULL
			   OR backend_xmin IS NOT NULL
			   OR state = 'idle in transaction')
	]);
is($ordinary_holders, '0',
	'no ordinary backend remains to hold the retention floor before VACUUM');

my $datfrozenxid_before = $node->safe_psql(
	'postgres',
	q[
		SELECT datfrozenxid::text::bigint
		FROM pg_database
		WHERE datname = current_database()
	]);

$node->safe_psql('template0', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');
$node->safe_psql('template1', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');
$node->safe_psql('postgres',
	'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

my $datfrozenxid_after = $node->safe_psql(
	'postgres',
	q[
		SELECT datfrozenxid::text::bigint
		FROM pg_database
		WHERE datname = current_database()
	]);
cmp_ok($datfrozenxid_after, '>', $datfrozenxid_before,
	'retention-pressure VACUUM advances current-database datfrozenxid while the prepared xid is outstanding');

$status_during = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$prepared_xid'::xid8);");
is($status_during, 'in progress',
	'prepared xid remains reportable after truncation pressure');

$prepared_visible = $node->safe_psql(
	'postgres',
	"SELECT count(*) FROM csnlog_truncate_test WHERE payload = '$prepared_payload';");
is($prepared_visible, '0',
	'prepared rows stay invisible while the witness remains outstanding');

$node->safe_psql('postgres', "COMMIT PREPARED '$prepared_gid';");

my $status_committed = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$prepared_xid'::xid8);");
like($status_committed, qr/^(?:committed)?$/,
	'committed prepared xid is either reportable or unavailable before restart once truncation pressure has advanced past retained status history');

$prepared_visible = $node->safe_psql(
	'postgres',
	"SELECT count(*) FROM csnlog_truncate_test WHERE payload = '$prepared_payload';");
is($prepared_visible, '1',
	'prepared rows become visible after COMMIT PREPARED');

my $prepared_remaining = $node->safe_psql(
	'postgres',
	"SELECT count(*) FROM pg_prepared_xacts WHERE gid = '$prepared_gid';");
is($prepared_remaining, '0',
	'prepared transaction disappears from pg_prepared_xacts after commit');

$node->pgbench(
	'--no-vacuum --client=4 --jobs=4 --transactions=25000',
	0,
	[],
	[],
	'pgbench post-release churn batch',
	$post_release_churn_script);

$node->safe_psql('postgres', 'CHECKPOINT');

$node->safe_psql('template0', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');
$node->safe_psql('template1', 'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');
$node->safe_psql('postgres',
	'VACUUM (FREEZE, DISABLE_PAGE_SKIPPING);');

$status_committed = $node->safe_psql(
	'postgres',
	"SELECT pg_xact_status('$prepared_xid'::xid8);");
like($status_committed, qr/^(?:committed)?$/,
	'committed prepared xid is either reportable or unavailable before restart after post-release vacuum');

$prepared_visible = $node->safe_psql(
	'postgres',
	"SELECT count(*) FROM csnlog_truncate_test WHERE payload = '$prepared_payload';");
is($prepared_visible, '1',
	'committed prepared rows remain visible through post-release vacuum');
$node->safe_psql('postgres',
	'ALTER DATABASE template0 ALLOW_CONNECTIONS false;');

$node->stop('immediate');
$node->start();

my ($ret, $stdout, $stderr) = $node->psql(
	'postgres',
	"SELECT pg_xact_status('$prepared_xid'::xid8);");
is($ret, 0, 'post-restart xid status lookup does not error');
like($stdout, qr/^(?:committed)?\n?$/,
	'post-restart xid status is either committed or unavailable');

my $row_count = $node->safe_psql(
	'postgres',
	'SELECT count(*) FROM csnlog_truncate_test;');
is($row_count, '300001',
	'all generated rows and the committed prepared row survive restart');

done_testing();
