#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/dwb
#
# IDENTIFICATION
#    src/backend/storage/dwb/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/dwb
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	dwb.o \
	dwb_ctl.o \
	dwb_file.o \
	dwb_recovery.o \
	dwb_retire.o

include $(top_srcdir)/src/backend/common.mk
